name: build-and-push
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      REPO_OWNER: oet-rumi
      REPO_NAME: cesium_cjs-rumi
      IMAGE_TAG: main
    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        run: |
          echo "IMAGE=${REGISTRY}/${REPO_OWNER}/${REPO_NAME}:${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
